# Generated by Django 5.0.2 on 2024-02-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='ans',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='quest',
        ),
    ]
