# Generated by Django 5.0.2 on 2024-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subplan_subplanfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplan',
            name='highlight_status',
        ),
        migrations.RemoveField(
            model_name='subplan',
            name='max_member',
        ),
        migrations.RemoveField(
            model_name='subplan',
            name='validity_days',
        ),
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
