# Generated by Django 5.0.2 on 2024-03-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_notifuserstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifuserstatus',
            options={},
        ),
    ]
