# Generated by Django 5.0.2 on 2024-03-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_notifuserstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifuserstatus',
            options={'verbose_name_plural': 'Notification Status'},
        ),
    ]
